name: Deploy

on: 
  workflow_call:
    inputs:
      projectName:
        description: Name of the project
        required: true
        type: string

jobs:
  deploy-github-pages:
    name: Github Pages
    runs-on: ubuntu-latest
    environment:
      name: Develop
      url: ${{ steps.deployment.outputs.page_url }}
    env:
      targetPlatform: WebGL
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup github pages
        uses: actions/configure-pages@v2.1.3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.projectName }}${{ env.targetPlatform }}
          path: build/${{ env.targetPlatform }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1.0.6
        with:
          # ${{ inputs.projectName }} in "path" input is needed because of build name
          # Check "buildName" input of "game-ci/unity-builder" action
          path: build/${{ env.targetPlatform }}/${{ inputs.projectName }}
          name: ${{ inputs.projectName }}${{ env.targetPlatform }}GithubPages 

      - name: Deploy to github pages
        id: deployment
        uses: actions/deploy-pages@v1.2.3
        with:
          artifact_name: ${{ inputs.projectName }}${{ env.targetPlatform }}GithubPages