name: Unity

on: [pull_request, workflow_dispatch]

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
    secrets: inherit
  build:
    name: Build
    needs: test
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      projectName: "WizardSpells"